services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: crmdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - crm-network

  crm_project:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/crmdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_APPLICATION_NAME: crm-project
    depends_on:
      - db
    networks:
      - crm-network

volumes:
  db-data:

networks:
  crm-network:
    driver: bridge
